@_default:
    just --list

build:
    #!/usr/bin/env bash

    if [ ! -f logo.png ]; then \
        just logo; \
    fi

    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "GitHub" \
        --quiet \
        https://github.com/jefftriplett?tab=projects \
        build

    rsync \
        --archive \
        --delete-after \
        --quiet \
        build/GitHub-darwin-*/GitHub.app/ \
        ~/Applications/GitHub.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget \
        --quiet \
        --output-document=logo.png \
        https://logo.clearbit.com/github.com

@upgrade:
    nativefier \
        --quiet \
        --upgrade \
        build/GitHub-darwin-*/GitHub.app/

    rsync \
        --archive \
        --delete-after \
        --quiet \
        build/GitHub-darwin-*/GitHub.app/ \
        ~/Applications/GitHub.app
