@_default:
    just --list

@build:
    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "GitHub" \
        https://github.com/jefftriplett?tab=projects \
        build

    rsync -av --delete-after \
        build/GitHub-darwin-x64/GitHub.app/ \
        ~/Applications/GitHub.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget --output-document=logo.png https://logo.clearbit.com/github.com

@upgrade:
    nativefier \
        --upgrade \
        build/GitHub-darwin-x64/GitHub.app/

    rsync -av --delete-after \
        build/GitHub-darwin-x64/GitHub.app/ \
        ~/Applications/GitHub.app
