---

- name: Copy reverse proxy settings
  copy:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
  tags: nginx

- name: Create log folder
  file:
    path: /var/log/nginx
    state: directory
  tags: nginx

- name: Create html folder
  file:
    path: /usr/local/etc/nginx/html
    state: directory
  tags: nginx

- name: Copy place holder page
  copy:
    src: 502.html
    dest: /usr/local/etc/nginx/html/502.html
  tags: nginx
