---

- name: Remove Sublime config dir if it exists
  tags: sublime
  file:
    path: "~/Library/Application Support/Sublime Text 3/Packages/User"
    state: absent

- name: Symlink Sublime Text config
  tags: sublime
  file:
    src: "~/.homesick/repos/dotfiles/configs/sublime_text"
    dest: "~/Library/Application Support/Sublime Text 3/Packages/User"
    force: yes
    state: link

- name: Symlink Sublime Text to subl in terminal
  tags: sublime
  file:
    src: "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
    dest: "{{ lookup('env','HOME') }}/bin/subl"
    state: link
