links = [
    "home/.actrc",
    "home/.bash_profile",
    "home/.bashrc",
    "home/.bashrc.d",
    "home/.claude",
    "home/.claude.json",
    "home/.codex",
    "home/.config/direnv",
    "home/.copilot",
    "home/.foreman",
    "home/.gitlab.yml",
    "home/.hammerspoon",
    "home/.idea",
    "home/.isort.cfg",
    "home/.justfiles",
    "home/.maid",
    "home/.personal.gitconfig",
    "home/.pip",
    "home/.plists",
    "home/.proselintrc.json",
    "home/.stglobalignore",
    "home/.stignore",
    "home/.tabset",
    "home/.teamocil",
    "home/.tmux",
    "home/.tmux.conf",
    "home/.topframe",
    "home/bin",
    "home/brew-manager.py",
    "home/Brewfile",
    "home/justfile",
    "home/minica-key.pem",
    "home/minica.pem",
    "home/package.json",
]
