cp ~/.stignore /Users/jefftriplett/.virtualenvs/2023.djangocon.us/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/2024.djangocon.us/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/aider-chat/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/aimmmbot/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/alfred-workflow/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/amazon-kindle-bulk-downloader/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/amazon-products/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/awesome-django/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/backups/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/black_out/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/bootstrap-to-tailwindcss/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/calendar-agent/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/chattts/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/claude-engineer/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/claude-to-sqlite/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/codedocs/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/countdown/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/defna.org/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-autoresponder/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-bylaws/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-div/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-fett/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-forge/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-form-builder/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-herd/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-jobs/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-llm/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-logos/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-lorebook/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-mcp/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-news.com/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-startproject/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-top-100/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-trademark-agent/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/django-webring/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangobook.com/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangocon-archive-project/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangocon-grorg/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangocon.us/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangoconus-automation/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangomcp/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangopackages/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangotv.com/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/djangox-pro-docs/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/dracula/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/durham.djangocon.us/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/files-to-claude-xml/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/flux/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/frontmatter-cli/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/frontmatter-issues/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/gpt-engineer/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/hubcap/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/jefftriplett-defaults/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/jefftriplett.com/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/jefftriplett.github.io/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/lfk.im/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/libredirect/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/llm-filesystem/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/llm-playground/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/mastodon-bookmark-export/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/mastodon-filter/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/modelcontextprotocol-servers/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/neapolitan/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/noiselith/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/ollama/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/plata/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/podcast-downloader/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/project-screenshots/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/psf-conduct-wg/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/pyvideo/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/revsys-alphakit/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/revsys-django-friendship/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/revsys-django-health-check/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/revsys-django-test-plus/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/revsys-revsys/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/revsys-surplussales/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/rumps/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/scraper_proxy/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/screenshot-to-code/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/servers/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/sitemap-scraper/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/sweep/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/syncthing/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/telegram-bot/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/templatemaker/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/toggl/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/tools/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/trailhawks.com/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/ultima/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/upgradedjango.com/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-assets/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-cms/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-directory/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-django-email-relay/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-django-q-registry/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-django-simple-nav/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-django-twc-project/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-django-twc-toolbox/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-django-twc-ui/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-docker-template/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-forsythia/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-lease/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-lodge/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-minerals/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-neapolitan/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-onboarding/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/westerveltco-spi/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/whisper/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/writing-bot/src/.stignore
cp ~/.stignore /Users/jefftriplett/.virtualenvs/youtube-to-frontmatter/src/.stignore
