"""Merge a per-machine Sublime settings overlay over the shared file.

Usage: merge.py SHARED OVERLAY OUT
Both inputs may hold comments and trailing commas, as Sublime allows.
"""

import json
import sys

import json5

shared, overlay, out = sys.argv[1:4]
with open(shared) as f:
    settings = json5.load(f)
with open(overlay) as f:
    settings.update(json5.load(f))
with open(out, "w") as f:
    f.write("// Generated by `just macos::sublime-link`: the shared preferences\n")
    f.write("// with this machine's overrides applied. Edit the files in\n")
    f.write("// home/.config/sublime-text/ instead, then rerun the recipe.\n")
    json.dump(settings, f, indent="\t", ensure_ascii=False)
    f.write("\n")
