# shellcheck shell=bash

alias alex="npx alex"
alias all-contributors-cli="npx all-contributors-cli"
alias brew-outdated="brew outdated --fetch-HEAD"
alias cat="bat -p"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias codeowners-enforcer="npx codeowners-enforcer"
alias embedme="npx embedme"
alias gam="~/bin/gam/gam"
alias gist="gist -p"
alias gitignore="npx gitignore"
alias got="git"
alias nanoprobe="npx nanoprobe"
alias npkill="npx npkill"
alias npm-check="npx npm-check"
alias nw="~/node_modules/nwjs/nwjs.app/Contents/MacOS/nwjs"
alias okimdone="npx okimdone"
alias outdated="brew update; brew outdated; brew cask outdated; mas outdated"
alias pip-outdated="PIP_REQUIRE_VIRTUALENV=false python -m pip list --outdated"
alias readme-md-generator="npx readme-md-generator"
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias vmd="npx vmd"
