tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "nektos/tap"
tap "tomanthony/brews"
brew "aria2"
brew "asdf"
brew "automake"
brew "bash"
brew "bat"
brew "bower"
brew "caddy"
brew "chrome-cli"
brew "coreutils"
brew "direnv"
brew "docker-compose"
brew "docker-slim"
brew "docker"
brew "dockutil"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "gist"
brew "git-flow"
brew "git-open"
brew "git-standup"
brew "git"
brew "gnupg"
brew "go"
brew "graphviz"
brew "guetzli"
brew "hadolint"
brew "helm"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "jack"
brew "jq"
brew "kubernetes-cli"
brew "libev"
brew "libgit2"
brew "libidn"
brew "lua"
brew "mas"
brew "maven"
brew "modd"
brew "mosh"
brew "mysql"
brew "nativefier"
brew "nektos/tap/act"
brew "nginx"
brew "nodenv"
brew "pandoc"
brew "parallel"
brew "pinentry-mac"
brew "pip-completion"
brew "pngpaste"
brew "postgresql", restart_service: true
brew "pre-commit"
brew "prettier"
brew "pyenv-ccache"
brew "pyenv-virtualenvwrapper"
brew "pyenv"
brew "qt"
brew "rbenv"
brew "redis"
brew "rename"
brew "rust"
brew "screenfetch"
brew "shellcheck"
brew "speexdsp"
brew "starship"
brew "terminal-notifier"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "tomanthony/brews/itermocil"
brew "tor"
brew "tree"
brew "unison"
brew "up"
brew "webkit2png"
brew "wget"
brew "whalebrew"
brew "xvid"
brew "yarn"
brew "youtube-dl"
brew "zlib"
cask "1password-cli"
cask "adobe-air"
cask "alfred"
cask "appcleaner"
cask "aws-vault"
cask "background-music"
cask "balenaetcher"
cask "bluestacks"
cask "charles"
cask "chicken"
cask "chromedriver"
cask "clipy"
cask "controlplane"
cask "dash"
cask "displaycal"
cask "elgato-game-capture-hd"
cask "font-cascadia"
cask "gitup"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-hangouts"
cask "iterm2"
cask "java"
cask "kindle"
cask "monitorcontrol"
cask "visual-studio-code"
mas "1Blocker", id: 1107421413
mas "1Keyboard", id: 766939888
mas "Affiliate", id: 789724698
mas "Airmail", id: 918858936
mas "Annotate", id: 918207447
mas "Bear", id: 1091189122
mas "Clean", id: 418412301
mas "Deckset", id: 847496013
mas "Directive", id: 1503550067
mas "Evernote", id: 406056744
mas "Fenêtre Lite", id: 1288451627
mas "Front and Center", id: 1493996622
mas "GarageBand", id: 682658836
mas "Helium", id: 1054607607
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kiwi for Gmail", id: 986304488
mas "Meeter", id: 1510445899
mas "Microsoft Remote Desktop", id: 1295203466
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager", id: 451907568
mas "Pixelmator Pro", id: 1289583905
mas "Pixelmator", id: 407963104
mas "Quiver", id: 866773894
mas "ReadKit", id: 588726889
mas "ScreenFocus", id: 1337028713
mas "Skitch", id: 425955336
mas "SnippetsLab", id: 1006087419
mas "Textual IRC Client", id: 1262957439
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "ToothFairy", id: 1191449274
mas "Trello", id: 1278508951
mas "Webcam Settings Control", id: 1172053162
mas "Whalebird", id: 1378283354
mas "WIP", id: 1456413506
mas "Xcode", id: 497799835
whalebrew "whalebrew/whalesay"
