@_default:
    just --list

@build:
    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "ChatGPT" \
        https://chat.openai.com/chat \
        build

    rsync -av --delete-after \
        build/ChatGPT-darwin-*/ChatGPT.app/ \
        ~/Applications/ChatGPT.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget --output-document=logo.png https://logo.clearbit.com/chat.openai.com

@upgrade:
    nativefier \
        --upgrade \
        build/ChatGPT-darwin-*/ChatGPT.app/

    rsync -av --delete-after \
        build/ChatGPT-darwin-*/ChatGPT.app/ \
        ~/Applications/ChatGPT.app
