@_default:
    just --list

build:
    #!/usr/bin/env bash

    if [ ! -f logo.png ]; then \
        just logo; \
    fi

    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "NovelAI" \
        --quiet \
        https://novelai.net/stories \
        build

    rsync \
        --archive \
        --delete-after \
        --quiet \
        build/NovelAI-darwin-*/NovelAI.app/ \
        ~/Applications/NovelAI.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget \
        --output-document=logo.png \
        --quiet \
        https://logo.clearbit.com/novelai.net

@upgrade:
    nativefier \
        --quiet \
        --upgrade \
        build/NovelAI-darwin-*/NovelAI.app/

    rsync \
        --archive \
        --delete-after \
        --quiet \
        build/NovelAI-darwin-*/NovelAI.app/ \
        ~/Applications/NovelAI.app
