@_default:
    just --list

@build:
    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "NovelAI" \
        https://novelai.net/stories \
        build

    rsync -av --delete-after \
        build/NovelAI-darwin-x64/NovelAI.app/ \
        ~/Applications/NovelAI.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget --output-document=logo.png https://logo.clearbit.com/novelai.net

@upgrade:
    nativefier \
        --upgrade \
        build/NovelAI-darwin-x64/NovelAI.app/

    rsync -av --delete-after \
        build/NovelAI-darwin-x64/NovelAI.app/ \
        ~/Applications/NovelAI.app
