---

- name: Install pipx Requirements
  tags:
    - pipx
    - python
  command: "pipx install {{ item.name }}"
  args:
    creates: "~/.local/pipx/venvs/{{ item.name }}"
  ignore_errors: True
  with_items: "{{ pipx_packages }}"
  # extra_args: --upgrade
