---

# - name: Install PyEnv
#   tags:
#     - python
#     - pyenv
#   homebrew:
#     name: "{{ item.name }}"
#     state: present
#   with_items:
#     - pyenv
#     - ccache
#     - zlib
#     - readline

- name: Install PyEnv plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - repo: "https://github.com/yyuu/pyenv-ccache.git"
      dest: "~/.pyenv/plugins/pyenv-ccache"
    - repo: "https://github.com/yyuu/pyenv-doctor.git"
      dest: "~/.pyenv/plugins/pyenv-doctor"
    - repo: "https://github.com/yyuu/pyenv-pip-migrate.git"
      dest: "~/.pyenv/plugins/pyenv-pip-migrate"
    - repo: "https://github.com/yyuu/pyenv-update.git"
      dest: "~/.pyenv/plugins/pyenv-update"
    - repo: "https://github.com/yyuu/pyenv-virtualenv.git"
      dest: "~/.pyenv/plugins/pyenv-virtualenv"
    - repo: "https://github.com/yyuu/pyenv-virtualenvwrapper.git"
      dest: "~/.pyenv/plugins/pyenv-virtualenvwrapper"
    - repo: "https://github.com/yyuu/pyenv-which-ext.git"
      dest: "~/.pyenv/plugins/pyenv-which-ext"
  tags:
    - python
    - pyenv

- name: Update PyEnv
  command: pyenv update
  tags:
    - python
    - pyenv

- name: Install Python Versions
  #environment:
  #  CFLAGS: "-I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include"
  #  LDFLAGS: "-L$(brew --prefix openssl)/lib"
  command: pyenv install {{ item.name }}
  args:
    creates: "~/.pyenv/versions/{{ item.name }}"
  with_items: "{{ pyenv_versions }}"
  tags:
    - python
    - pyenv

- name: Set system-level Python versions
  command: pyenv global {{ pyenv_versions|join(" ") }}
  tags:
    - python
    - pyenv
