---

- name: Update Homebrew
  tags:
    - homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: no

- name: Install Taps
  tags:
    - homebrew
    - homebrew-taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - buo/cask-upgrade
    - caskroom/cask
    - caskroom/fonts
    - caskroom/versions
    - homebrew/command-not-found
    - homebrew/dupes
    - homebrew/services
    - homebrew/versions
    - jimbojsb/launchrocket
    - watsonbox/cmu-sphinx

- name: Install Apps
  tags:
    - homebrew
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - aria2
    - ccache
    - chrome-cli
    - coreutils
    - direnv
    - gist
    - git
    - git-standup
    - go
    - gpg
    - gpg-agent
    - keybase
    - libev
    - phantomjs
    - pinentry-mac
    - pyenv
    - rbenv
    - readline
    - ruby-build
    - sqlite
    - sshrc
    - wget

- name: Install Mac Apps
  tags:
    - homebrew
    - homebrew-casks
    - casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - appcleaner
    - arq
    - bartender
    - calibre
    - caprine
    - charles
    - chicken
    - cleanmymac
    - coconutbattery
    - controlplane
    - corectl-app
    - duet
    - fluid
    - font-hack
    - font-ubuntu
    - font-ubuntu-mono-derivative-powerline
    - gitup
    - google-chrome
    - google-featured-photos
    - google-hangouts
    - gpgtools
    - hammerspoon
    - handbrake
    - handbrakebatch
    - iterm2
    - jadengeller-helium
    - java
    - karabiner
    - kube-solo
    - launchrocket
    - mactex
    - mattr-slate
    - medis
    - minecraft
    - mojibar
    - numi
    - plex-media-player
    - plex-media-server
    - reggy
    - resilio-sync
    - seil
    - skype
    - slack
    - sling
    - spotify
    - sqlitebrowser
    - sublime-text
    - tableflip
    - timemachineeditor
    - tower
    - transmission
    - vagrant
    - vagrant-manager
    - virtualbox
    - vlc
    - wkhtmltopdf
    - xld
    - xquartz

- name: Homebrew Cask Cleanup
  tags:
    - homebrew
    - homebrew-casks
    - casks
  command: brew cask cleanup

- name: Homebrew Cleanup
  tags:
    - homebrew
    - homebrew-cleanup
  command: brew cleanup
