@_default:
    just --list

@build:
    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "Mastodon" \
        https://mastodon.social/ \
        build

    rsync -av --delete-after \
        build/Mastodon-darwin-x64/Mastodon.app/ \
        ~/Applications/Mastodon.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget --output-document=logo.png https://logo.clearbit.com/mastodon.social

@upgrade:
    nativefier \
        --upgrade \
        build/Mastodon-darwin-x64/Mastodon.app/

    rsync -av --delete-after \
        build/Mastodon-darwin-x64/Mastodon.app/ \
        ~/Applications/Mastodon.app
