@_default:
    just --list

build:
    #!/usr/bin/env bash

    if [ ! -f logo.png ]; then \
        just logo; \
    fi

    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "Mastodon" \
        --quiet \
        https://mastodon.social/ \
        build

    rsync \
        --archive \
        --delete-after \
        --quiet \
        build/Mastodon-darwin-*/Mastodon.app/ \
        ~/Applications/Mastodon.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget \
        --quiet \
        --output-document=logo.png \
        https://logo.clearbit.com/mastodon.social

@upgrade:
    nativefier \
        --quiet \
        --upgrade \
        build/Mastodon-darwin-*/Mastodon.app/

    rsync \
        --archive \
        --delete-after \
        --quiet \
        build/Mastodon-darwin-*/Mastodon.app/ \
        ~/Applications/Mastodon.app
