#!/bin/bash
# This hook is run during the startup phase when loading virtualenvwrapper.sh.
VIRTUAL_ENV_NAME=$(basename "${VIRTUAL_ENV}")

# Set PROJECT_HOME if not already set
if [ -z "${PROJECT_HOME}" ]; then
  export PROJECT_HOME="${HOME}/Projects"
fi

# Ensure PROJECT_HOME directory exists
if [ ! -d "${PROJECT_HOME}" ]; then
  mkdir -p "${PROJECT_HOME}"
fi

just --justfile=${HOME}/justfile virtualenvwrapper::initialize
