#!/bin/bash
# This hook is run after every virtualenv is deactivated.
unset DATABASE_URL
unset DJANGO_SETTINGS_MODULE

# Set user.badge back to our default when exiting the virtualenv
export USER_BADGE="${USER_BADGE_DEFAULT}"

if ! [ -e tabset ]; then
  # npx iterm2-tab-set --title "❓"
  tabset --title "❓"
fi

just --justfile=${HOME}/justfile _postdeactivate
