#!/bin/bash
# This hook is run after a new project is activated.

VIRTUAL_ENV_NAME=$(basename "${VIRTUAL_ENV}")
PROJECT_SRC="${PROJECT_HOME}/${VIRTUAL_ENV_NAME}"
PROJECT_ENVRC="${PROJECT_SRC}/.envrc"
PROJECT_PYRIGHTCONFIG="${PROJECT_SRC}/pyrightconfig.json"

echo "WORKON_HOME==${WORKON_HOME}"
echo "PROJECT_SRC==${PROJECT_SRC}"
echo "PROJECT_ENVRC==${PROJECT_ENVRC}"
echo "PROJECT_PYRIGHTCONFIG==${PROJECT_PYRIGHTCONFIG}"

if [ -d "${PROJECT_SRC}" ]; then
    mkdir -p "${PROJECT_SRC}"
fi

# ------------------------------------------------------------
# Sublime Text Project ".sublime-project" file...
# ------------------------------------------------------------

if command -v subl-projects >/dev/null 2>&1; then
  if [ -d "${PROJECT_SRC}" ]; then
    subl-projects add "${VIRTUAL_ENV_NAME}" "${PROJECT_SRC}"
  fi
fi

# ------------------------------------------------------------
# Sublime Text LSP PyRight ".pyrightconfig.json" file...
# ------------------------------------------------------------
if [[ -d "$PROJECT_SRC" && ! -e "$PROJECT_PYRIGHTCONFIG" ]]; then
  if command -v jq >/dev/null 2>&1; then
    echo "Creating ${PROJECT_PYRIGHTCONFIG}"
    echo "{\"venvPath\": \"${WORKON_HOME}\", \"venv\": \"${VIRTUAL_ENV_NAME}\"}" | jq > "${PROJECT_PYRIGHTCONFIG}"
  fi
fi

just --justfile=${HOME}/justfile virtualenvwrapper::postmkproject
