#!/bin/bash
# This hook is run after a new project is created and before it is activated.

VIRTUAL_ENV_NAME=$(basename "${VIRTUAL_ENV}")

PROJECT_SRC="${PROJECT_HOME}/${VIRTUAL_ENV_NAME}"
PROJECT_ENVRC="${PROJECT_SRC}/.envrc"
PROJECT_PYRIGHTCONFIG="${PROJECT_SRC}/pyrightconfig.json"
PROJECT_STIGNORE="${PROJECT_SRC}/.stignore"

echo "WORKON_HOME==${WORKON_HOME}"
echo "PROJECT_SRC==${PROJECT_SRC}"
echo "PROJECT_ENVRC==${PROJECT_ENVRC}"
echo "PROJECT_PYRIGHTCONFIG==${PROJECT_PYRIGHTCONFIG}"
echo "PROJECT_STIGNORE==${PROJECT_STIGNORE}"

if [ -d "$PROJECT_SRC" ]; then
    mkdir -p $PROJECT_SRC
fi

just --justfile=${HOME}/justfile virtualenvwrapper::premkproject
