#!/bin/bash
# This hook is run before a virtualenv is deleted.

VIRTUAL_ENV_NAME=$(basename "${VIRTUAL_ENV}")

read -p "or am I deleting ${VIRTUAL_ENV_NAME}? " -n 1 -r response

CONTINUE=false

echo

if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
  CONTINUE=true
fi

if $CONTINUE; then
  if command -v subl-projects >/dev/null 2>&1; then
    subl-projects delete "${VIRTUAL_ENV_NAME}" --force 2>/dev/null || true
  fi
fi

just --justfile=${HOME}/justfile virtualenvwrapper::prermvirtualenv
