#!/bin/sh
# This hook is run before a virtualenv is deleted.

VIRTUAL_ENV_NAME=$(basename "${VIRTUAL_ENV}")

read -p "or am I deleting ${VIRTUAL_ENV_NAME}? " -n 1 -r response

CONTINUE=false

echo

if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
  CONTINUE=true
fi

PROJECT_FILE="${HOME}/Library/Application Support/Sublime Text 3/Packages/User/Projects/${VIRTUAL_ENV_NAME}.sublime-project"
WORKSPACE_FILE="${HOME}/Library/Application Support/Sublime Text 3/Packages/User/Projects/${VIRTUAL_ENV_NAME}.sublime-workspace"

if $CONTINUE; then
  if [ -e "${PROJECT_FILE}" ]; then
    rm "${PROJECT_FILE}"
  fi

  if [ -e "${WORKSPACE_FILE}" ]; then
    rm "${WORKSPACE_FILE}"
  fi
fi
