@_default:
    just --list

@build:
    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "Grammarly" \
        https://app.grammarly.com/ \
        build

    rsync -av --delete-after \
        build/Grammarly-darwin-*/Grammarly.app/ \
        ~/Applications/Grammarly.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget --output-document=logo.png https://logo.clearbit.com/grammarly.com

@upgrade:
    nativefier \
        --upgrade \
        build/Grammarly-darwin-*/Grammarly.app/

    rsync -av --delete-after \
        build/Grammarly-darwin-*/Grammarly.app/ \
        ~/Applications/Grammarly.app
