@_default:
    just --list

build:
    #!/usr/bin/env bash

    if [ ! -f logo.png ]; then \
        just logo; \
    fi

    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "Grammarly" \
        --quiet \
        https://app.grammarly.com/ \
        build

    rsync \
        --archive \
        --delete-after \
        --quiet \
        build/Grammarly-darwin-*/Grammarly.app/ \
        ~/Applications/Grammarly.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget \
        --quiet \
        --output-document=logo.png \
        https://logo.clearbit.com/grammarly.com

@upgrade:
    nativefier \
        --quiet \
        --upgrade \
        build/Grammarly-darwin-*/Grammarly.app/

    rsync \
        --archive \
        --delete-after \
        --quiet \
        build/Grammarly-darwin-*/Grammarly.app/ \
        ~/Applications/Grammarly.app
