# ----------------------------------------------------------------
# macOS recipes
# ----------------------------------------------------------------

set dotenv-load := false
set export

justfile := justfile_directory() + "/.justfiles/macos.justfile"

# list all available recipes
[private]
@default:
    just --justfile {{ justfile }} --list

# format this justfile
[private]
@fmt:
    just --justfile {{ justfile }} --fmt

# ----------------------------------------------------------------
# Time Machine recipes
# ----------------------------------------------------------------

# boost Time Machine backup speed by increasing IO priority
@timemachine-boost:
    # bump IO priority to finish more quickly
    # https://apple.stackexchange.com/questions/382772/time-machine-in-the-cleaning-up-state-forever

    sudo sysctl debug.lowpri_throttle_enabled=0

# restore normal IO priority after Time Machine backup completes
@timemachine-boost-complete:
    # once done
    sudo sysctl debug.lowpri_throttle_enabled=1

# delete specific Time Machine backups
@timemachine-delete +ARGS:
    sudo tmutil delete {{ ARGS }}

# list all Time Machine backups
@timemachine-list:
    sudo tmutil listbackups

# ----------------------------------------------------------------
# Xcode
# ----------------------------------------------------------------

# install Xcode command line tools
@xcode-bootstrap:
    sudo xcode-select --install

# upgrade Xcode command line tools by removing and reinstalling
@xcode-upgrade:
    sudo rm -rf /Library/Developer/CommandLineTools
    just --justfile {{ justfile }} xcode-bootstrap

# ----------------------------------------------------------------
# Default applications (duti)
# ----------------------------------------------------------------

# set default applications for file types using duti
@duti-setup:
    brew install duti

    # 3D printing
    duti -s com.bambulab.bambu-studio .stl all
    duti -s com.bambulab.bambu-studio .3mf all

# ----------------------------------------------------------------
# Screenshots
# ----------------------------------------------------------------

screenshots_dir := env_var("HOME") + "/Screenshots"

# save new screenshots to ~/Screenshots instead of the iCloud-synced Desktop
screenshots-setup:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ screenshots_dir }}"
    defaults write com.apple.screencapture location -string "{{ screenshots_dir }}"
    killall SystemUIServer
    echo "screenshots now save to $(defaults read com.apple.screencapture location)"

# move screenshots that landed on the Desktop into ~/Screenshots (never overwrites)
screenshots-sweep:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ screenshots_dir }}"
    shopt -s nullglob nocaseglob
    moved=0
    for f in "${HOME}"/Desktop/Screenshot*.png "${HOME}"/Desktop/Screen\ Shot*.png "${HOME}"/Desktop/CleanShot*.png "${HOME}"/Desktop/Screen\ Recording*.mov; do
        mv -n "${f}" "{{ screenshots_dir }}/" && moved=$((moved + 1))
    done
    echo "moved ${moved} file(s) to {{ screenshots_dir }}"

# ----------------------------------------------------------------
# Sublime Text
# ----------------------------------------------------------------

HOST := `hostname -s`
sublime_user := env_var("HOME") + "/Library/Application Support/Sublime Text/Packages/User"
sublime_repo := justfile_directory() + "/.config/sublime-text"

# link the Sublime Text settings into Packages/User; a Preferences.<Host> overlay is merged in
sublime-link:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p "{{ sublime_user }}"
    prefs="Preferences.sublime-settings"
    overlay="{{ sublime_repo }}/Preferences.{{ HOST }}.sublime-settings"
    dst="{{ sublime_user }}/${prefs}"
    if [[ -f "${overlay}" ]]; then
        # a generated real file, not a link: the shared file plus this machine's keys
        [[ -L "${dst}" ]] && rm "${dst}"
        uv run --quiet --with json5 "{{ sublime_repo }}/merge.py" "{{ sublime_repo }}/${prefs}" "${overlay}" "${dst}"
        echo "generated ${prefs} with the {{ HOST }} overlay"
    else
        src="{{ sublime_repo }}/${prefs}"
        if [[ -L "${dst}" ]]; then
            ln -sfn "${src}" "${dst}"; echo "relinked ${prefs}"
        elif [[ -e "${dst}" ]]; then
            if head -1 "${dst}" | grep -q "Generated by"; then
                rm "${dst}"; ln -s "${src}" "${dst}"; echo "linked ${prefs} (overlay removed)"
            else
                echo "kept local ${prefs}; compare with: diff \"${dst}\" \"${src}\""
            fi
        else
            ln -s "${src}" "${dst}"; echo "linked ${prefs}"
        fi
    fi
    name="Package Control.sublime-settings"
    src="{{ sublime_repo }}/${name}"
    dst="{{ sublime_user }}/${name}"
    if [[ -L "${dst}" ]]; then
        ln -sfn "${src}" "${dst}"; echo "relinked ${name}"
    elif [[ -e "${dst}" ]]; then
        echo "kept local ${name}; compare with: diff \"${dst}\" \"${src}\""
    else
        ln -s "${src}" "${dst}"; echo "linked ${name}"
    fi

# show how the local Sublime Text settings differ from the dotfiles
sublime-diff:
    #!/usr/bin/env bash
    for name in "Preferences.sublime-settings" "Package Control.sublime-settings"; do
        echo "== ${name}"
        diff "{{ sublime_user }}/${name}" "{{ sublime_repo }}/${name}" && echo "identical"
    done
