@_default:
    just --list

@_cmd *ARGS="--help":
    cd github && just {{ ARGS }}
    cd grammarly && just {{ ARGS }}
    cd mastodon && just {{ ARGS }}
    cd toggl && just {{ ARGS }}

@build:
    just _cmd build

@clean:
    just _cmd clean

@fmt:
    just --fmt --unstable

@upgrade:
    just _cmd upgrade
