@_default:
    just --list

@_cmd *ARGS="--help":
    for folder in `ls .`; do \
        if [ -d "$folder" ]; then \
            cd $folder && just {{ ARGS }} && cd ..; \
        fi \
    done

@build:
    just _cmd build

@clean:
    just _cmd clean

@fmt:
    just --fmt --unstable
    just _cmd fmt

@logo:
    just _cmd logo

@upgrade:
    just _cmd upgrade
