@_default:
    just --list

@build:
    nativefier \
        --darwin-dark-mode-support \
        --icon logo.png \
        --lang "en-US" \
        --name "Toggl" \
        https://www.toggl.com/app \
        build

    rsync -av --delete-after \
        build/Toggl-darwin-x64/Toggl.app/ \
        ~/Applications/Toggl.app

@clean:
    rm -rf build

@fmt:
    just --fmt --unstable

@logo:
    wget --output-document=logo.png https://logo.clearbit.com/www.toggl.com

@upgrade:
    nativefier \
        --upgrade \
        build/Toggl-darwin-x64/Toggl.app/

    rsync -av --delete-after \
        build/Toggl-darwin-x64/Toggl.app/ \
        ~/Applications/Toggl.app
