---

- name: Set standby delay to 24 hours (default is 1 hour)
  sudo: yes
  command: pmset -a standbydelay 86400

- name: Disable the sound effects on boot
  sudo: yes
  command: nvram SystemAudioVolume=" "

- name: Disable the “Are you sure you want to open this application?” dialog
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false

- name: Don’t display the annoying prompt when quitting iTerm
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: bool
    value: false

- name: Finder - show all filename extensions
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: QLEnableTextSelection
  osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true

- name: Display full POSIX path as Finder window title
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

- name: Disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Empty trash securely
  osx_defaults:
    domain: com.apple.finder
    key: EmptyTrashSecurely
    type: bool
    value: false

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Always show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: false

- name: Dock no-glass
  osx_defaults:
    domain: com.apple.dock
    key: no-glass
    type: bool
    value: true

- name: dock mcx-expose-disabled
  osx_defaults:
    domain: com.apple.dock
    key: mcx-expose-disabled
    type: bool
    value: true

# Bottom left screen corner → Start screen saver

- name: dock wvous-bl-corner
  osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: 5

- name: dock wvous-bl-modifier
  osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: 0
